export default {
  _init: false,
  phonemes: {
    // C: ["p", "t", "k", "m", "n", "l", "s"],
    // V: ["a", "e", "i", "o", "u"],
    // S: ["s"],
    // F: ["m", "n"],
    // L: ["r", "l"],
  },
  structure: "CVC",
  exponent: 2,
  restricts: [],
  cortho: {},
  vortho: {},
  noortho: false,
  nomorph: false,
  nowordpool: false,
  minsyll: 1,
  maxsyll: 1,
  morphemes: {},
  words: {},
  names: [],
  joiner: " ",
  maxchar: 12,
  minchar: 5, 
  cityNames: [],
  landNames: [],
  fullWords: [],
}