export const REMOVE_LANGUAGE = "REMOVE_LANGUAGE"

export const CREATE_LANGUAGE = "CREATE_LANGUAGE"
export const CONFIG_LANGUAGE = "CONFIG_LANGUAGE"

export const GENERATE_LANGUAGE = "GENERATE_LANGUAGE"
export const GENERATE_WORDS = "GENERATE_WORDS"
export const REMOVE_WORD = "REMOVE_WORD"
export const REMOVE_WORDS = "REMOVE_WORDS"
export const GENERATE_NAMES = "GENERATE_NAMES"
export const REMOVE_NAME = "REMOVE_NAME"
export const REMOVE_NAMES = "REMOVE_NAMES"